add code smell and technical debt section
220328-uta-sh-net-ext/training-code pull request #5
Opened 2022-05-11 16:21 UTC by SteveBurgos95

2022-05-11 16:33 UTC, kaurrevature commented on 4-DevOps/Reportings/Vanquish/Reports.md
> +# Types of Code Smells
You might want to explain one liners about the types of code smells if possible

2022-05-11 16:33 UTC, kaurrevature requested changes
I also hope some demo would be there to show some code smells

2022-05-11 20:00 UTC, SteveBurgos95 commented on 4-DevOps/Reportings/Vanquish/Reports.md
> +# Types of Code Smells
Added explanation one liners about the types of code smells

2022-05-13 20:36 UTC, kaurrevature requested changes
good jon @SteveBurgos95 
And Kudos to team vanquish!

2022-05-13 20:37 UTC, merged

2022-05-16 15:19 UTC, kaurrevature reviewed
Good work